In [1]:
import numpy as np
from IPython.display import Image
from qutip import (Qobj, about, basis, coherent, coherent_dm, create, destroy,
                   expect, fock, fock_dm, mesolve, qeye, sigmax, sigmay,
                   sigmaz, tensor, thermal_dm, anim_matrix_histogram,
                   anim_fock_distribution)

## Fundamental 

#### Playing around with QuTip for the first time

In [ ]:
q = Qobj([[1],[1]])

print(q.dims, q.shape, q.type)

op = Qobj([[1 + 1j,2 + 1j],[4,1]])

print('eigenenergies: ',op.eigenenergies())

NameError: name 'Qobj' is not defined

## Basis Vectors

In [4]:
N = 4 # number of modes
n = 2 # number of photons

state = basis (N,n)
state

Quantum object: dims=[[4], [1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [0.]
 [1.]
 [0.]]

In [5]:
fock(4,2)

Quantum object: dims=[[4], [1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [0.]
 [1.]
 [0.]]

In [ ]:
coherent(30, alpha = 2)

Quantum object: dims=[[30], [1]], shape=(30, 1), type='ket', dtype=Dense
Qobj data =
[[1.35335283e-01]
 [2.70670566e-01]
 [3.82785986e-01]
 [4.42003184e-01]
 [4.42003184e-01]
 [3.95339666e-01]
 [3.22793486e-01]
 [2.44008940e-01]
 [1.72540376e-01]
 [1.15026917e-01]
 [7.27494101e-02]
 [4.38695449e-02]
 [2.53280936e-02]
 [1.40494985e-02]
 [7.50977282e-03]
 [3.87803001e-03]
 [1.93901501e-03]
 [9.40560433e-04]
 [4.43384440e-04]
 [2.03438733e-04]
 [9.09805674e-05]
 [3.97071751e-05]
 [1.69311956e-05]
 [7.06079956e-06]
 [2.88254871e-06]
 [1.15305673e-06]
 [4.52141399e-07]
 [1.74428430e-07]
 [6.47047818e-08]
 [2.76188397e-08]]

In [8]:
coherent(10, alpha = 2)

Quantum object: dims=[[10], [1]], shape=(10, 1), type='ket', dtype=Dense
Qobj data =
[[0.13533468]
 [0.27067598]
 [0.38275331]
 [0.44215515]
 [0.4414275 ]
 [0.39717038]
 [0.31781378]
 [0.25575028]
 [0.14827955]
 [0.15941954]]

In [22]:
# density matrices

coherent_dm(2,1)

coherent_dm(4,3).eigenenergies()

array([-6.21450822e-17, -1.30579902e-17,  5.01412036e-17,  1.00000000e+00])

In [ ]:
sigmax()


Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR, isherm=True
Qobj data =
[[0. 1.]
 [1. 0.]]